spring:
  sql:
    init:
      mode: always
      continue-on-error: false
      separator: ';'
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: centinal_test
    password: postpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20          # Higher for time-series workloads
      minimum-idle: 5
      idle-timeout: 300000           # 5 minutes
      max-lifetime: 1200000          # 20 minutes
      connection-timeout: 20000      # 20 seconds
      leak-detection-threshold: 60000 # 1 minute
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 50             # Optimize batch inserts for time-series
        order_inserts: true
        order_updates: true
    open-in-view: true
  kafka:
    consumer:
      group-id: market-data-consumer
      auto-offset-reset: earliest
      enable-auto-commit: false
    producer:
      acks: 1
      retries: 3
    listener:
      ack-mode: manual
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
# Market Data Configuration
market:
  data:
    uri: 'wss://ws-feed.exchange.coinbase.com'
    symbols: BTC-USD,ETH-USD,ADA-USD,SOL-USD

